<?php 


return [

	'title'	=> 'imprint',



	'title2'	=> 'According to § 5 TMG',

	'title3'	=> 'Represented by',

	'phone'	=> 'Phone',

	'title4'	=> 'Disclaimer',

	'title5'	=> 'Liability for content',

	'p5'	    => 'The contents of our pages were created with great care. However, we can not assume any liability for the accuracy, completeness and timeliness of the content. As a service provider we are responsible according to § 7 Abs.1 TMG for own contents on these sides according to the general laws. According to §§ 8 to 10 TMG, however, we as a service provider are not obliged to monitor transmitted or stored external information or to investigate circumstances that indicate illegal activity. Obligations to remove or block the use of information under general law remain unaffected. A liability in this regard, however, is only possible from the date of knowledge of a specific infringement. Upon notification of appropriate violations, we will remove this content immediately.',


	'title6'	=> 'Liability for links',

	'p6'	    => 'Our offer contains links to external websites of third parties on whose contents we have no influence. Therefore, we can not assume any liability for these external contents. The respective provider or operator of the pages is always responsible for the contents of the linked pages. The linked pages were checked for possible legal violations at the time of linking. Illegal content was not recognizable at the time of linking. However, a permanent content control of the linked pages is not reasonable without concrete evidence of an infringement. Upon notification of violations, we will remove such links immediately.',

	'title7'	=> 'Copyright',

	'p7'		=> 'The content and works on these pages created by the site operators are subject to German copyright law. The reproduction, processing, distribution and any kind of exploitation outside the limits of copyright require the written consent of the respective author or creator. Downloads and copies of this site are for private, non-commercial use only. As far as the contents on this side were not created by the operator, the copyrights of third parties are considered. In particular contents of third parties are marked as such. If you should still be aware of a copyright infringement, we ask for a note. Upon notification of violations, we will remove such content immediately.',

	'title8'	=> 'Data Protection',
	'p8'	    => 'The use of our website is usually possible without providing personal information. As far as on our sides personal data (for example name, address or eMail addresses) are raised, this takes place, as far as possible, always on freiwilliger basis. These data will not be disclosed to third parties without your explicit consent.
Please note that data transmission over the Internet (for example, when communicating via e-mail) may have security vulnerabilities. A complete protection of the data from access by third parties is not possible.
The use of contact data published in the context of the imprint obligation by third parties for sending unsolicited advertising and information materials is hereby expressly excluded. The operators of the pages expressly reserve the right to take legal action in the event of the unsolicited sending of advertising information, such as spam e-mails.',


	'title9'	=> 'Google Analytics',
	'p9'	    => 'This website uses Google Analytics, a web analytics service provided by Google Inc. ("Google"). Google Analytics uses so-called "cookies", text files that are stored on your computer and that allow an analysis of the use of the website by you. The information generated by the cookie about your use of this website (including your IP address) is transmitted to and stored by Google on servers in the United States. Google will use this information to evaluate your use of the website, to compile reports on website activity for website operators and to provide other services related to website activity and internet usage. Google may also transfer this information to third parties if required by law or as far as third parties process this data on behalf of Google. Google will in no case associate your IP address with other Google data. You can prevent the installation of cookies by setting your browser software accordingly; however, please note that in this case you may not be able to use all features of this website to the fullest extent. By using this website, you consent to the processing of data about you by Google in the manner and for the purposes set out above.',


	'title10'	=> 'Google AdSense',
	'p10'		=> 'This website uses Google Adsense, a web advertising service of Google Inc., USA ("Google"). Google Adsense uses so-called "cookies" (text files) which are stored on your computer and which allows an analysis of the use of the website by you. Google Adsense also uses so-called "web beacons" (small invisible graphics) to gather information. By using the web beacon, simple actions such as visitor traffic on the website can be recorded and collected. The information generated by the cookie and / or web beacon about your use of this website (including your IP address) will be transmitted to and stored by Google on servers in the United States. Google will use this information to evaluate your use of the website in terms of advertising, to compile reports on website activity and advertisements for website operators, and to provide other services related to website activity and internet usage. Google may also transfer this information to third parties if required by law or as far as third parties process this data on behalf of Google. Google will in no case associate your IP address with other Google data. You can prevent the storage of cookies on your hard disk and the display of web beacons by selecting "Do not accept cookies" in your browser settings (in MS Internet Explorer, under "Tools> Internet Options> Privacy> Settings" in Firefox under "Tools> Settings> Privacy> Cookies"); however, please note that in this case you may not be able to use all features of this website to the fullest extent. By using this website, you consent to the processing of data about you by Google in the manner and for the purposes set out above.',
	



];